# # # # # # # # # # #
# Author: kcin      #
# cfg version: 1.0  #
# # # # # # # # # # #
resistance-rework-enabled: true
resistance-rework:
  world: lobby
plotspatch-enabled: true
plotspatch:
  world: plots
